# Generated by Django 5.1.4 on 2024-12-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('tamaño', models.FloatField(verbose_name='')),
                ('precio', models.FloatField(verbose_name='')),
                ('calidad', models.CharField(max_length=10)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('peso', models.FloatField(verbose_name='')),
            ],
        ),
    ]
