# Generated by Django 5.1.4 on 2024-12-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_Local', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('capacidad', models.CharField(max_length=10)),
                ('empleados', models.CharField(max_length=10)),
                ('dueño', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=10)),
                ('telefono', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
