# Generated by Django 5.1.4 on 2024-12-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.PositiveSmallIntegerField()),
                ('id_cliente', models.PositiveSmallIntegerField()),
                ('fecha_venta', models.DateField()),
                ('cantidad', models.FloatField(verbose_name='')),
                ('total', models.FloatField(verbose_name='')),
            ],
        ),
    ]
