# Generated by Django 5.1.4 on 2024-12-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('productos', models.CharField(max_length=10)),
                ('historial', models.CharField(max_length=10)),
                ('metodo_pago', models.CharField(max_length=10)),
                ('telefono', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
