# Generated by Django 5.1.4 on 2024-12-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('sueldo', models.FloatField(verbose_name='')),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
